<?php

namespace pocketmine\item;

class Item419 {

	const TOTEM_OF_UNDYING = 558;
	const STONE = 1;
	const GRASS = 2;
	const DIRT = 3;
	const COBBLE = 4;
	const WOODEN_PLANKS = 5;
	const SAPLINGS = 6;
	const BEDROCK = 7;
	const WATER = 8;
	const STILL_WATER = 9;
	const LAVA = 10;
	const STILL_LAVA = 11;
	const SAND = 12;
	const GRAVEL = 13;
	const GOLD_ORE = 14;
	const IRON_ORE = 15;
	const COAL_ORE = 16;
	const TRUNK = 17;
	const LEAVE = 18;
	const SPONGE = 19;
	const GLASS = 20;
	const LAPIS_ORE = 21;
	const LAPIS_BLOCK = 22;
	const DISPENSER = 23;
	const SANDSTONE = 24;
	const NOTE_BLOCK = 25;
	const BED_BLOCK = 26;
	const POWERED_RAIL = 27;
	const DETECTOR_RAIL = 28;
	const STICKY_PISTON = 29;
	const COBWEB = 30;
	const TALL_GRASS = 31;
	const DEAD_BUSH = 32;
	const WOOL = 35;
	const DANDELION = 37;
	const RED_FLOWER = 38;
	const BROWN_MUSHROOM = 39;
	const RED_MUSHROOM = 40;
	const GOLD_BLOCK = 41;
	const IRON_BLOCK = 42;
	const DOUBLE_SLABS = 43;
	const SLABS = 44;
	const BRICKS_BLOCK = 45;
	const TNT = 46;
	const BOOKSHELF = 47;
	const MOSSY_STONE = 48;
	const OBSIDIAN = 49;
	const TORCH = 50;
	const FIRE = 51;
	const MONSTER_SPAWNER = 52;
	const OAK_WOODEN_STAIRS = 53;
	const CHEST = 54;
	const REDSTONE_WIRE = 55;
	const DIAMOND_ORE = 56;
	const DIAMOND_BLOCK = 57;
	const WORKBENCH = 58;
	const WHEAT_BLOCK = 59;
	const FARMLAND = 60;
	const FURNACE = 61;
	const LIT_FURNACE = 62;
	const SIGN_POST = 63;
	const WOOD_DOOR_BLOCK = 64;
	const LADDER = 65;
	const RAIL = 66;
	const COBBLESTONE_STAIRS = 67;
	const WALL_SIGN = 68;
	const LEVER = 69;
	const STONE_PRESSURE_PLATE = 70;
	const IRON_DOOR_BLOCK = 71;
	const WOODEN_PRESSURE_PLATE = 72;
	const REDSTONE_ORE = 73;
	const LIT_REDSTONE_ORE = 74;
	const REDSTONE_TORCH = 75;
	const REDSTONE_TORCH_ACTIVE = 76;
	const STONE_BUTTON = 77;
	const SNOW_LAYER = 78;
	const ICE = 79;
	const SNOW_BLOCK = 80;
	const CACTUS = 81;
	const CLAY_BLOCK = 82;
	const SUGARCANE_BLOCK = 83;
	const JUKEBOX = 84;
	const FENCE = 85;
	const PUMPKIN = 86;
	const NETHERRACK = 87;
	const SOUL_SAND = 88;
	const GLOWSTONE_BLOCK = 89;
	const PORTAL = 90;
	const JACK_O_LANTERN = 91;
	const CAKE_BLOCK = 92;
	const REDSTONE_REPEATER_BLOCK = 93;
	const REDSTONE_REPEATER_BLOCK_ACTIVE = 94;
	const INVISIBLE_BEDROCK = 95;
	const TRAPDOOR = 96;
	const MONSTER_EGG = 97;
	const STONE_BRICK = 98;
	const BROWN_MUSHROOM_BLOCK = 99;
	const RED_MUSHROOM_BLOCK = 100;
	const IRON_BARS = 101;
	const GLASS_PANEL = 102;
	const MELON_BLOCK = 103;
	const PUMPKIN_STEM = 104;
	const MELON_STEM = 105;
	const VINES = 106;
	const FENCE_GATE = 107;
	const BRICK_STAIRS = 108;
	const STONE_BRICK_STAIRS = 109;
	const MYCELIUM = 110;
	const LILY_PAD = 111;
	const NETHER_BRICK_BLOCK = 112;
	const NETHER_BRICK_FENCE = 113;
	const NETHER_BRICKS_STAIRS = 114;
	const NETHER_WART_BLOCK = 115;
	const ENCHANTMENT_TABLE = 116;
	const BREWING_STAND_BLOCK = 117;
	const CAULDRON_BLOCK = 118;
	const END_PORTAL = 120;
	const END_STONE = 121;
	const DRAGON_EGG = 122;
	const REDSTONE_LAMP = 123;
	const REDSTONE_LAMP_ACTIVE = 124;
	const DROPPER = 125;
	const ACTIVATOR_RAIL = 126;
	const COCOA = 127;
	const SANDSTONE_STAIRS = 128;
	const EMERALD_ORE = 129;
	const ENDER_CHEST = 130;
	const TRIPWIRE_HOOK = 131;
	const TRIPWIRE = 132;
	const EMERALD_BLOCK = 133;
	const SPRUCE_WOODEN_STAIRS = 134;
	const BIRCH_WOODEN_STAIRS = 135;
	const JUNGLE_WOODEN_STAIRS = 136;
	const BEACON = 138;
	const COBBLESTONE_WALL = 139;
	const FLOWER_POT_BLOCK = 140;
	const CARROT_BLOCK = 141;
	const POTATO_BLOCK = 142;
	const WOODEN_BUTTON = 143;
	const MOB_HEAD_BLOCK = 144;
	const ANVIL = 145;
	const TRAPPED_CHEST = 146;
	const WEIGHTED_PRESSURE_PLATE_LIGHT = 147;
	const WEIGHTED_PRESSURE_PLATE_HEAVY = 148;
	const REDSTONE_COMPARATOR_BLOCK = 149;
	const REDSTONE_COMPARATOR_BLOCK_POWERED = 150;
	const DAYLIGHT_SENSOR = 151;
	const REDSTONE_BLOCK = 152;
	const NETHER_QUARTZ_ORE = 153;
	const HOPPER_BLOCK = 154;
	const QUARTZ_BLOCK = 155;
	const QUARTZ_STAIRS = 156;
	const DOUBLE_WOODEN_SLABS = 157;
	const WOODEN_SLABS = 158;
	const STAINED_HARDENED_CLAY = 159;
	const STAINED_GLASS_PANE = 160;
	const LEAVE2 = 161;
	const LOG2 = 162;
	const ACACIA_WOODEN_STAIRS = 163;
	const DARK_OAK_WOODEN_STAIRS = 164;
	const SLIME_BLOCK = 165;
	const IRON_TRAPDOOR = 167;
	const PRISMARINE = 168;
	const SEA_LANTERN = 169;
	const HAY_BALE = 170;
	const CARPET = 171;
	const HARDENED_CLAY = 172;
	const COAL_BLOCK = 173;
	const PACKED_ICE = 174;
	const DOUBLE_PLANT = 175;
	const STANDING_BANNER = 176;
	const WALL_BANNER = 177;
	const INVERTED_DAYLIGHT_SENSOR = 178;
	const RED_SANDSTONE = 179;
	const RED_SANDSTONE_STAIRS = 180;
	const DOUBLE_RED_SANDSTONE_SLAB = 181;
	const RED_SANDSTONE_SLAB = 182;
	const FENCE_GATE_SPRUCE = 183;
	const FENCE_GATE_BIRCH = 184;
	const FENCE_GATE_JUNGLE = 185;
	const FENCE_GATE_DARK_OAK = 186;
	const FENCE_GATE_ACACIA = 187;
	const SPRUCE_DOOR_BLOCK = 193;
	const BIRCH_DOOR_BLOCK = 194;
	const JUNGLE_DOOR_BLOCK = 195;
	const ACACIA_DOOR_BLOCK = 196;
	const DARK_OAK_DOOR_BLOCK = 197;
	const GRASS_PATH = 198;
	const ITEM_FRAME_BLOCK = 199;
	const CHORUS_FLOWER = 200;
	const PURPUR_BLOCK = 201;
	const END_BRICKS = 206;
	const END_ROD = 208;
	const MAGMA = 213;
	const NETHER_WART_BLOCK_BLOCK = 214;
	const RED_NETHER_BRICK = 215;
	const BONE_BLOCK = 216;
	const SHULKER_BOX = 218;
	const CHORUS_PLANT = 240;
	const STAINED_GLASS = 241;
	const PODZOL = 243;
	const BEETROOT_BLOCK = 244;
	const STONECUTTER = 245;
	const GLOWING_OBSIDIAN = 246;
	const NETHER_REACTOR = 247;
	const IRON_SHOVEL = 296;
	const IRON_PICKAXE = 297;
	const IRON_AXE = 298;
	const FLINT_AND_STEEL = 299;
	const APPLE = 257;
	const BOW = 300;
	const ARROW = 301;
	const COAL = 302;
	const DIAMOND = 304;
	const IRON_INGOT = 305;
	const GOLD_INGOT = 306;
	const IRON_SWORD = 307;
	const WOODEN_SWORD = 308;
	const WOODEN_SHOVEL = 309;
	const WOODEN_PICKAXE = 310;
	const WOODEN_AXE = 311;
	const STONE_SWORD = 312;
	const STONE_SHOVEL = 313;
	const STONE_PICKAXE = 314;
	const STONE_AXE = 315;
	const DIAMOND_SWORD = 316;
	const DIAMOND_SHOVEL = 317;
	const DIAMOND_PICKAXE = 318;
	const DIAMOND_AXE = 319;
	const STICKS = 320;
	const BOWL = 321;
	const MUSHROOM_STEW = 260;
	const GOLDEN_SWORD = 322;
	const GOLDEN_SHOVEL = 323;
	const GOLDEN_PICKAXE = 324;
	const GOLDEN_AXE = 325;
	const STRING = 326;
	const FEATHER = 327;
	const GUNPOWDER = 328;
	const WOODEN_HOE = 329;
	const STONE_HOE = 330;
	const IRON_HOE = 331;
	const DIAMOND_HOE = 332;
	const GOLDEN_HOE = 333;
	const WHEAT_SEEDS = 291;
	const WHEAT = 334;
	const BREAD = 261;
	const LEATHER_CAP = 335;
	const LEATHER_TUNIC = 336;
	const LEATHER_PANTS = 337;
	const LEATHER_BOOTS = 338;
	const CHAIN_HELMET = 339;
	const CHAIN_CHESTPLATE = 340;
	const CHAIN_LEGGINGS = 341;
	const CHAIN_BOOTS = 342;
	const IRON_HELMET = 343;
	const IRON_CHESTPLATE = 344;
	const IRON_LEGGINGS = 345;
	const IRON_BOOTS = 346;
	const DIAMOND_HELMET = 347;
	const DIAMOND_CHESTPLATE = 348;
	const DIAMOND_LEGGINGS = 349;
	const DIAMOND_BOOTS = 350;
	const GOLD_HELMET = 351;
	const GOLD_CHESTPLATE = 352;
	const GOLD_LEGGINGS = 353;
	const GOLD_BOOTS = 354;
	const FLINT = 356;
	const RAW_PORKCHOP = 262;
	const COOKED_PORKCHOP = 263;
	const SHIELD = 355;	
	const PAINTING = 357;
	const GOLDEN_APPLE = 258;
	const WOODEN_DOOR = 359;
	const BUCKET = 360;
	const MINECART = 368;
	const SADDLE = 369;
	const IRON_DOOR = 370;
	const REDSTONE_DUST = 371;
	const SNOWBALL = 372;
	const BOAT = 612;
	const LEATHER = 379;
	const BRICK = 381;
	const CLAY = 382;
	const PAPER = 384;
	const BOOK = 385;
	const SLIMEBALL = 386;
	const MINECART_WITH_CHEST = 387;
	const EGG = 388;
	const COMPASS = 389;
	const FISHING_ROD = 390;
	const CLOCK = 391;
	const GLOWSTONE_DUST = 392;
	const DYE = 613;
	const BLACK_DYE = 393; //meta 16
 	const RED_DYE = 394; // meta 1
	const GREEN_DYE = 395; //  meta 2 
	const BROWN_DYE = 396; //meta 17
	const BLUE_DYE = 397; // meta 18
	const PURPLE_DYE = 398; //meta 5
	const CYAN_DYE = 399; //meta 6
	const LIGHT_GRAY_DYE = 400; //meta 7
	const GRAY_DYE = 401; //meta 8
	const PINK_DYE = 402; // meta 9
	const LIME_DYE = 403; // meta 10
	const YELLOW_DYE = 404; // meta 11
	const LIGHT_BLUE_DYE = 405; // meta 12
	const MAGENTA_DYE = 406; // meta 13
	const ORANGE_DYE = 407; // meta 14
	const WHITE_DYE = 408; // meta 19
	const BONE_MEAL = 409; //meta 15
	const COCOA_BEANS = 410; //meta 3
	const INC_SAC = 411; // meta 0
	const LAPIS_LAZULI = 412; // meta 4
	const BONE = 413;
	const SUGAR = 414;
	const CAKE = 415;
	const BED = 416;
	const REDSTONE_REPEATER = 417;
	const COOKIE = 271;
	const SHEARS = 419;
	const PUMPKIN_SEEDS = 292;
	const MELON_SEEDS = 293;
	const RAW_BEEF = 273;
	const COOKED_BEEF = 274;
	const RAW_CHICKEN = 275;
	const COOKED_CHICKEN = 276;
	const ROTTEN_FLESH = 277;
	const ENDER_PERL = 420;
	const BLAZE_ROD = 421;
	const GHAST_TEAR = 422;
	const GOLDEN_NUGGET = 423;
	const NETHER_WART = 294;
	const POTION = 424;
	const GLASS_BOTTLE = 425;
	const SPIDER_EYE = 278;
	const FERMENTED_SPIDER_EYE = 426;
	const BLAZE_POWDER = 427;
	const MAGMA_CREAM = 428;
	const BREWING_STAND = 429;
	const CAULDRON = 430;
	const EYE_OF_ENDER = 431;
	const SPAWN_EGG = 615;
	const BOTTLE_ENCHANTING = 498;
	const WRITABLE_BOOK = 500;
	const WRITTEN_BOOK = 501;
	const EMERALD = 502;
	const ITEM_FRAME = 503;
	const FLOWER_POT = 504;
	const CARROTS = 279;
	const POTATOES = 280;
	const BAKED_POTATOES = 281;
	const POISONOUS_POTATO = 282;
	const GOLDEN_CARROT = 283;
	const MOB_HEAD = 506;
	const PUMPKIN_PIE = 284;
	const ENCHANTING_BOOK = 511;
	const REDSTONE_COMPARATOR = 512;
	const NETHER_BRICK = 513;
	const NETHER_QUARTZ = 514;
	const MINECART_WITH_TNT = 515;
	const MINECART_WITH_HOPPER = 516;
	const PRISMARINE_SHARD = 555;
	const HOPPER = 517;
	const RAW_RABBIT = 288;
	const COOKED_RABBIT = 289;
	const RABBIT_STEW = 290;
	const RABBIT_FOOT = 518;
	const RABBIT_HIDE = 519;
	const LEAD = 537;
	const NAME_TAG = 538;
	const PRISMARINE_CRYSTAL = 539;
	const END_CRYSTAL = 616;
	const SPRUCE_DOOR = 543;
	const BIRCH_DOOR = 544;
	const JUNGLE_DOOR = 545;
	const ACACIA_DOOR = 546;
	const DARK_OAK_DOOR = 547;
	const CHORUS_FRUIT = 548;
	const DRAGONS_BREATH = 550;
	const SPLASH_POTION = 551;
	const LINGERING_POTION = 552;
	const ELYTRA = 554;
	const SHULKER_SHELL = 556;
	const IRON_NUGGET = 559;
	const BEETROOT = 285;
	const BEETROOT_SEED = 295;
	const BEETROOT_SOUP = 286;
	const RAW_SALMON = 265;
	const PUFFERFISH = 267;
	const COOKED_SALMON = 269;
	const CAMERA = 583;
	const AIR = 0;
	const SIGN = 358;
	const SUGAR_CANES = 83;
	const RAW_FISH = 264;
	const COOKED_FISH = 268;
	const MELON_SLICE = 272;
	const EMPTY_MAP = 505;
	const CARROT_ON_STICK = 507;
	const LEATHER_HORSE_ARMOR = 520;
	const IRON_HORSE_ARMOR = 521;
	const GOLDEN_HORSE_ARMOR = 522;
	const DIAMOND_HORSE_ARMOR = 523;
	const RAW_MUTTON = 540;
	const COOKED_MUTTON = 541;
	const CLOWNFISH = 266;
	const ENCHANTED_GOLDEN_APPLE = 259;
	const GLISTERING_MELON = 432;
	CONST OAK_WOOD_STAIRS = 53;
	const FILLED_MAP = 418;
	const NETHER_STAR = 508;
	const DISC_CHIRP = 527;
	const DISC_MALL = 529;
	const CHEST_MINECART = 387;
	const DISC_STRAD = 532;
	const DISC_WAIT = 535;
	const DISC_CAT = 525;	
	const DISC_13 = 524;
	const DISC_MELLOHI = 530;
	const RECORD_MELLOHI = 530;
	const DISC_11 = 534;
	const FIRE_CHARGE = 499;

	const COBBLESTONE = self::COBBLE;

	const PLANK = self::WOODEN_PLANKS;
	const SAPLING = self::SAPLINGS;

	const LOG = self::TRUNK;
	const LEAVES = self::LEAVE;
	const BUSH = self::DEAD_BUSH;

	const POPPY = self::RED_FLOWER;
	const DOUBLE_SLAB = self::DOUBLE_SLABS;
	const SLAB = self::SLABS;
	const BRICKS = self::BRICKS_BLOCK;
	const MOSS_STONE = self::MOSSY_STONE;

	const WOOD_STAIRS = self::OAK_WOODEN_STAIRS;
	const CRAFTING_TABLE = self::WORKBENCH;
	const BURNING_FURNACE = self::LIT_FURNACE;

	const WOODEN_DOOR_BLOCK = self::WOOD_DOOR_BLOCK;
	const DOOR_BLOCK = self::WOOD_DOOR_BLOCK;
	const COBBLE_STAIRS = self::COBBLESTONE_STAIRS;
	const GLOWING_REDSTONE_ORE = self::LIT_REDSTONE_ORE;
	const SNOW = self::SNOW_LAYER;
	const REEDS = self::SUGARCANE_BLOCK;
	const GLOWSTONE = self::GLOWSTONE_BLOCK;
	const LIT_PUMPKIN = self::JACK_O_LANTERN;
	const STONE_BRICKS = self::STONE_BRICK;
	const IRON_BAR = self::IRON_BARS;
	const GLASS_PANE = self::GLASS_PANEL;
	const VINE = self::VINES;
	const WATER_LILY = self::LILY_PAD;
	const NETHER_BRICKS = self::NETHER_BRICK_BLOCK;

	const ENCHANTING_TABLE = self::ENCHANTMENT_TABLE;
	const SPRUCE_WOOD_STAIRS = self::SPRUCE_WOODEN_STAIRS;
	const BIRCH_WOOD_STAIRS = self::BIRCH_WOODEN_STAIRS;
	const JUNGLE_WOOD_STAIRS = self::JUNGLE_WOODEN_STAIRS;

	const COBBLE_WALL = self::COBBLESTONE_WALL;
	const STONE_WALL = self::COBBLESTONE_WALL;
	const DOUBLE_WOOD_SLAB = self::DOUBLE_WOODEN_SLABS;

	const WOODEN_SLAB = self::WOODEN_SLABS;
	const WOOD_SLAB = self::WOODEN_SLABS;
	const STAINED_CLAY = self::STAINED_HARDENED_CLAY;
	const LEAVES2 = self::LEAVE2;

	
	const WOOD2 = self::LOG2;
	const TRUNK2 = self::LOG2;
	const ACACIA_WOOD_STAIRS = self::ACACIA_WOODEN_STAIRS;
	const DARK_OAK_WOOD_STAIRS = self::DARK_OAK_WOODEN_STAIRS;
	const DOUBLE_STONE_SLAB2 = self::DOUBLE_RED_SANDSTONE_SLAB;
	const STONE_SLAB2 = self::RED_SANDSTONE_SLAB;
	const FLINT_STEEL = self::FLINT_AND_STEEL;
	const STICK = self::STICKS;
	const GOLD_SWORD = self::GOLDEN_SWORD;
	const GOLD_SHOVEL = self::GOLDEN_SHOVEL;
	const GOLD_PICKAXE = self::GOLDEN_PICKAXE;
	const GOLD_AXE = self::GOLDEN_AXE;
	const GOLD_HOE = self::GOLDEN_HOE;
	const SEEDS = self::WHEAT_SEEDS;
	const REDSTONE = self::REDSTONE_DUST;

	const SUGARCANE = self::SUGAR_CANES;
	const MELON = self::MELON_SLICE;
	const STEAK = self::COOKED_BEEF;
	const GOLD_NUGGET = self::GOLDEN_NUGGET;
	const CARROT = self::CARROTS;
	const POTATO = self::POTATOES;
	const BAKED_POTATO = self::BAKED_POTATOES;
	const QUARTZ = self::NETHER_QUARTZ;
	const BEETROOT_SEEDS = self::BEETROOT_SEED;
	const ENCHANT_TABLE = self::ENCHANTING_TABLE;
	const WOODEN_PLANK = self::WOODEN_PLANKS;
	const WOOD = self::TRUNK;
	const WOODEN_STAIRS = self::WOOD_STAIRS;

	const DYES = [
		self::INC_SAC,
		self::RED_DYE,
		self::GREEN_DYE,
		self::COCOA_BEANS,
		self::LAPIS_LAZULI,
		self::PURPLE_DYE,
		self::CYAN_DYE,
		self::LIGHT_GRAY_DYE,
		self::GRAY_DYE,
		self::PINK_DYE,
		self::LIME_DYE,
		self::YELLOW_DYE,
		self::LIGHT_BLUE_DYE,
		self::MAGENTA_DYE,
		self::ORANGE_DYE,
		self::BONE_MEAL,
		self::BLACK_DYE,
		self::BROWN_DYE,
		self::BLUE_DYE,
		self::WHITE_DYE,
	];

	protected static $names419 = [
		1 => "Stone",
		2 => "Grass",
		3 => "Dirt",
		4 => "Cobblestone",
		5 => "Plank",
		6 => "Sapling",
		7 => "Bedrock",
		8 => "Water",
		9 => "Still Water",
		10 => "Lava",
		11 => "Still Lava",
		12 => "Sand",
		13 => "Gravel",
		14 => "Gold Ore",
		15 => "Iron Ore",
		16 => "Coal Ore",
		17 => "Wood",
		18 => "Leaves",
		19 => "Sponge",
		20 => "Glass",
		21 => "Lapis Ore",
		22 => "Lapis Block",
		23 => "undefined",
		24 => "Sandstone",
		25 => "undefined",
		26 => "Bed",
		27 => "undefined",
		28 => "undefined",
		29 => "undefined",
		30 => "Cobweb",
		31 => "Tall Grass",
		32 => "Bush",
		35 => "Wool",
		37 => "Dandelion",
		38 => "Red Flower",
		39 => "Brown Mushroom",
		40 => "Red Mushroom",
		41 => "Gold Block",
		42 => "Iron Block",
		43 => "Double Slab",
		44 => "Slab",
		45 => "Bricks",
		46 => "TNT",
		47 => "Bookshelf",
		48 => "Moss Stone",
		49 => "Obsidian",
		50 => "Torch",
		51 => "Fire",
		52 => "Monster Spawner",
		53 => "Wooden Stairs",
		54 => "Chest",
		55 => "undefined",
		56 => "Diamond Ore",
		57 => "Diamond Block",
		58 => "Crafting Table",
		59 => "Wheat Block",
		60 => "Farmland",
		61 => "Furnace",
		62 => "Burning Furnace",
		63 => "Sign Post",
		64 => "Door",
		65 => "Ladder",
		66 => "Rail",
		67 => "Cobble Stairs",
		68 => "Wall Sign",
		69 => "undefined",
		70 => "undefined",
		71 => "Iron Door",
		72 => "undefined",
		73 => "Redstone Ore",
		74 => "Glowing Redstone Ore",
		75 => "Redstone Torch",
		76 => "Glowing Redstone Torch",
		77 => "undefined",
		78 => "Snow",
		79 => "Ice",
		80 => "Snow Block",
		81 => "Cactus",
		82 => "Clay Block",
		83 => "Sugarcane Block",
		84 => "undefined",
		85 => "Fence",
		86 => "Pumpkin Block",
		87 => "Netherrack",
		88 => "Soul Sand",
		89 => "Glowstone",
		90 => "Portal",
		91 => "Jack-O'-Lantern",
		92 => "Cake Block",
		93 => "undefined",
		94 => "undefined",
		95 => "undefined",
		96 => "Trapdoor",
		97 => "undefined",
		98 => "Stone Bricks",
		99 => "Brown Mushroom Block",
		100 => "Red Mushroom Block",
		101 => "Iron Bar",
		102 => "Glass Panel",
		103 => "Melon BLock",
		104 => "Pumpkin Stem",
		105 => "undefined",
		106 => "Vine",
		107 => "Fence Gate",
		108 => "Brick Stairs",
		109 => "Stone Brick Stairs",
		110 => "Mycelium",
		111 => "Water Lily",
		112 => "Nether Brick",
		113 => "Nether Brick Fence",
		114 => "Nether Brick Stairs",
		115 => "undefined",
		116 => "Enchantment Table",
		117 => "Brewing Stand",
		118 => "Cauldron Block",
		120 => "End Portal",
		121 => "End Stone",
		122 => "Dragon Egg",
		123 => "Redstone Lamp",
		124 => "Redstone Lamp Active",
		125 => "Dropper",
		126 => "Activator Rail",
		127 => "Cocoa",
		128 => "Sendstone Stairs",
		129 => "Emerald Ore",
		130 => "Ender Chest",
		131 => "Tripwire Hook",
		132 => "Tripwire",
		133 => "Emerald Block",
		134 => "Spruce Wood Stairs",
		135 => "Birch Wood Stairs",
		136 => "Jungle Wood Stairs",
		138 => "Beacon",
		139 => "Cobblestone Wall",
		140 => "Flower Pot",
		141 => "Carrot Block",
		142 => "Potato Block",
		143 => "Wooden Button",
		144 => "Mob Head",
		145 => "Anvil",
		146 => "Trapped Chest",
		147 => "Weighted Pressure Plate Light",
		148 => "Weighted Pressure Plate Heavy",
		149 => "Redstone Comparator",
		150 => "Redstone Comparator Powered",
		151 => "Daylight Sensor",
		152 => "Redstone Block",
		153 => "Nether Quartz Ore",
		154 => "Hopper",
		155 => "Quartz Block",
		156 => "Quartz Stairs",
		157 => "Double Wood Slab",
		158 => "Wooden Slab",
		159 => "Stained Clay",
		160 => "Stained Glass Pane",
		161 => "Leaves2",
		162 => "Wood2",
		163 => "Acacia Wood Stairs",
		164 => "Dark Oak Wood Stairs",
		165 => "Slime Block",
		167 => "Iron Trapdoor",
		168 => "undefined",
		169 => "undefined",
		170 => "Hay Bale",
		171 => "Carpet",
		172 => "Hardened CLay",
		173 => "Coal BLock",
		174 => "undefined",
		175 => "Double Plant",
		176 => "undefined",
		177 => "undefined",
		178 => "Inverted Daylight Sensor",
		179 => "Red Sandstone",
		180 => "Red Sandstone Stairs",
		181 => "Double Red Sandstone Slab",
		182 => "Red Sandstone Slab",
		183 => "Fence Gate Spruce",
		184 => "Fence Gate Birch",
		185 => "Fence Gate Jungle",
		186 => "Fence Gate Dark Oak",
		187 => "Fence Gate Acacia",
		193 => "Wood Door Block",
		194 => "Birch Door",
		195 => "Jungle Door",
		196 => "Acacia Door",
		197 => "Dark Oak Door",
		198 => "Grass Path",
		199 => "undefined",
		200 => "Chorus Flower",
		201 => "Purpur Block",
		206 => "End Brick",
		208 => "End Rod",
		213 => "undefined",
		214 => "undefined",
		215 => "undefined",
		216 => "undefined",
		218 => "undefined",
		240 => "Chorus Plant",
		241 => "Stained Glass",
		243 => "Podzol",
		244 => "Beetroot Block",
		245 => "Stonecutter",
		246 => "Glowing Obsidian",
		247 => "Nether Reactor",
		296 => "Iron Shovel",
		297 => "Iron Pickaxe",
		298 => "Iron Axe",
		299 => "Flint and Steel",
		257 => "Apple",
		300 => "Bow",
		301 => "Arrow",
		302 => "Coal",
		304 => "Diamond",
		305 => "Iron Ingot",
		306 => "Gold Ingot",
		307 => "Iron Sword",
		308 => "Wooden Sword",
		309 => "Wooden Shovel",
		310 => "Wooden Pickaxe",
		311 => "Wooden Axe",
		312 => "Stone Sword",
		313 => "Stone Shovel",
		314 => "Stone Pickaxe",
		315 => "Stone Axe",
		316 => "Diamond Sword",
		317 => "Diamond Shovel",
		318 => "Diamond Pickaxe",
		319 => "Diamond Axe",
		320 => "Stick",
		321 => "Bowl",
		260 => "Mushroom Stew",
		322 => "Gold Sword",
		323 => "Gold Shovel",
		324 => "Gold Pickaxe",
		325 => "Gold Axe",
		326 => "String",
		327 => "Feather",
		328 => "Gunpowder",
		329 => "Wooden Hoe",
		330 => "Stone Hoe",
		331 => "Iron Hoe",
		332 => "Diamond Hoe",
		333 => "Gold Hoe",
		291 => "Wheat Seed",
		334 => "Wheat",
		261 => "Bread",
		335 => "Leather Cap",
		336 => "Leather Tunic",
		337 => "Leather Pants",
		338 => "Leather Boots",
		339 => "Chain Helmet",
		340 => "Chain Chestplate",
		341 => "Chain Leggins",
		342 => "Chain Boots",
		343 => "Iron Helmet",
		344 => "Iron Chestplate",
		345 => "Iron Leggins",
		346 => "Iron Boots",
		347 => "Diamond Helmet",
		348 => "Diamond Chestplate",
		349 => "Diamond Leggins",
		350 => "Diamond Boots",
		351 => "Gold Helmet",
		352 => "Gold Chestplate",
		353 => "Gold Leggins",
		354 => "Gold Boots",
		355 => "Shield",
		356 => "Flint",
		262 => "Raw Porkchop",
		263 => "Cooked Porkchop",
		357 => "Painting",
		258 => "Golden Apple",
		359 => "Wooden Door",
		360 => "Bucket",
		368 => "Minecart",
		369 => "undefined",
		370 => "Iron Door",
		371 => "Redstone",
		372 => "Snowball",
		612 => "undefined",
		379 => "Leather",
		381 => "Bricks",
		382 => "Clay",
		384 => "Paper",
		385 => "Book",
		386 => "Slimeball",
		387 => "undefined",
		388 => "Egg",
		389 => "Compass",
		390 => "Compass",
		391 => "Clock",
		392 => "Glowstone Dust",
		613 => "Dye",
		393 => "Black Dye",
		394 => "Red Dye",
		395 => "Green Dye",
		396 => "Brown Dye",
		397 => "Blue Dye",
		398 => "Purple Dye",
		399 => "Cyan Dye",
		400 => "Light Gray Dye",
		401 => "Gray Dye",
		402 => "Pink Dye",
		403 => "Lime Dye",
		404 => "Yellow Dye",
		405 => "Light Blue Dye",
		406 => "Magenta Dye",
		407 => "Orange Dye",
		408 => "White Dye",
		409 => "Bone Meal",
		412 => "Lapis Lazuli",
		413 => "Bone",
		414 => "Sugar",
		415 => "Cake",
		416 => "Bed",
		417 => "undefined",
		271 => "Cookie",
		419 => "Shears",
		292 => "Pumpkin Seed",
		293 => "Melon Seed",
		273 => "Raw Beef",
		274 => "Steak",
		275 => "Raw Chicken",
		276 => "Cooked Chicken",
		277 => "undefined",
		420 => "undefined",
		421 => "Blaze Rod",
		422 => "undefined",
		423 => "Gold Nugget",
		294 => "undefined",
		424 => "Potion",
		425 => "undefined",
		278 => "undefined",
		426 => "undefined",
		427 => "Blaze powder",
		428 => "Magma Cream",
		429 => "undefined",
		430 => "undefined",
		431 => "undefined",
		615 => "Spawn Egg",
		498 => "undefined",
		500 => "Book & Quill",
		501 => "Written Book",
		502 => "Emerald",
		503 => "undefined",
		504 => "Flower Pot",
		279 => "Carrot",
		280 => "Potato",
		281 => "Baked Potato",
		282 => "Poisonous Potato",
		283 => "Golden Carrot",
		506 => "Mob Head",
		284 => "Pumpkin Pie",
		511 => "Enchanted Book",
		512 => "Redstone Comparator",
		513 => "Nether Bricks",
		514 => "Quartz",
		515 => "Minecart with TNT",
		516 => "Minecart with Hopper",
		555 => "undefined",
		517 => "Hopper",
		288 => "Raw Rabbit",
		289 => "Cooked Rabbit",
		290 => "undefined",
		518 => "Rabbit's Foot",
		519 => "Rabbit Hide",
		537 => "Lead",
		538 => "Name Tag",
		539 => "Prismarine Crystal",
		616 => "undefined",
		543 => "Spruce Door",
		544 => "Birch Door",
		545 => "Jungle Door",
		546 => "Acacia Door",
		547 => "Dark Oak Door",
		548 => "undefined",
		550 => "undefined",
		551 => "Splash Potion",
		552 => "undefined",
		554 => "undefined",
		556 => "undefined",
		559 => "undefined",
		285 => "Beetroot",
		295 => "Beetroot Seed",
		286 => "Beetroot Soup",
		265 => "Raw Salmon",
		267 => "Pufferfish",
		269 => "Cooked Salmon",
		583 => "Camera",
		0 => "Air",
		358 => "Sign",
		83 => "Sugarcane",
		264 => "Raw Cod ",
		268 => "Cooked Fish",
		272 => "Melon",
		505 => "Empty Map",
		507 => "Carrot on a Stick",
		520 => "Leather Horse Armor",
		521 => "Iron Horse Armor",
		522 => "Golden Horse Armor",
		523 => "Diamond Horse Armor",
		540 => "Raw Mutton",
		541 => "Cooked Mutton",
		266 => "Tropical Fish",
		259 => "Enchanted Golden Apple",
	];

	/*public static function getId($id) {
		if ($id < 256) {
			return $id;
		}
		if 
	}*/

	public static function getOldByNew($id) {
		if ($id < 256) {
			return $id;
		}
		if (in_array($id, self::DYES)) {
			return Item::DYE;
		}
		$oClass = new \ReflectionClass(__CLASS__);
		$new = $oClass->getConstants();
		$oClass = new \ReflectionClass('pocketmine\item\Item');
		$old = $oClass->getConstants();
		$key = array_search($id, $new);
		$key = explode('_', $key)[1];
		return $old[$key] ?? $id;
	}

	public static function getNewByOld($id, $meta) {
		if ($id < 256) {
			return $id;
		}
		if ($id == Item::DYE) {
			return self::DYES[$meta];
		}
		$oClass = new \ReflectionClass(__CLASS__);
		$new = $oClass->getConstants(); // Item419
		$oClass = new \ReflectionClass('pocketmine\item\Item');
		$old = $oClass->getConstants(); // Item
		$key = array_search($id, $old);
		if ($key) {
			$key = 'NEW_' . $key; // ??
			return $new[$key] ?? $id;
		} else {
			return $id;
		}
	}

	public static function getDyeMeta($id) {
		return array_search($id, self::DYES[$id]);
	}

}
